# Generated by Django 3.1.4 on 2021-06-05 07:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.FileField(upload_to='SharedFile/')),
            ],
        ),
        migrations.CreateModel(
            name='UserConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversationId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('messageReceiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userProfileIdOfTheMessageReceiver', to='UserProfiles.userprofile')),
                ('messageSender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userProfileIdOfTheMessageSender', to='UserProfiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('messageSentTime', models.DateTimeField(auto_now_add=True)),
                ('messageReceivedTime', models.DateTimeField(blank=True, null=True)),
                ('messageType', models.IntegerField(default=0)),
                ('messageContent', models.TextField()),
                ('messageStatus', models.IntegerField(default=1)),
                ('messageReadTime', models.DateTimeField(blank=True, null=True)),
                ('conversationId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserConversation.userconversation')),
            ],
        ),
    ]
