# Generated by Django 3.1.4 on 2021-06-05 07:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hashtags', '0001_initial'),
        ('UserProfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('commentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commentDescription', models.TextField()),
                ('commentTime', models.DateTimeField(auto_now_add=True)),
                ('commentStatus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('postContent', models.FileField(upload_to='UserPost/')),
                ('postDescription', models.TextField(blank=True, null=True)),
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('postStatus', models.IntegerField(default=0)),
                ('userProfileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('postTagId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.IntegerField(default=0)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postIdOfThePostWhichGotTags', to='UserPost.userpost')),
                ('taggedUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfileIdOfTheUserWhoGotTaggedInPost', to='UserProfiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PostSubComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCommentId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('commentDescription', models.TextField()),
                ('commentTime', models.DateTimeField(auto_now_add=True)),
                ('commentStatus', models.IntegerField(default=0)),
                ('parentComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserPost.postcomment')),
                ('userProfileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeTime', models.DateTimeField(auto_now_add=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postIdOfThePostWhichGotLiked', to='UserPost.userpost')),
                ('userProfileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfileIdOfTheUserWhoLiked', to='UserProfiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtagIdInThePostWhichAreUsed', to='Hashtags.hashtag')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postIdOfThePostWhichGotHashtag', to='UserPost.userpost')),
            ],
        ),
        migrations.AddField(
            model_name='postcomment',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postIdOfThePostWhichGotCommented', to='UserPost.userpost'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='userProfileId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfileIdOfTheUserWhoCommented', to='UserProfiles.userprofile'),
        ),
    ]
