# Generated by Django 3.0.8 on 2020-11-22 08:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfiles', '0001_initial'),
        ('Hashtags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('postContent', models.FileField(upload_to='UserPost/')),
                ('postDescription', models.TextField(null=True)),
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('postStatus', models.IntegerField(default=0)),
                ('userProfileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfiles.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('postTagId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postIdOfThePostWhichGotTags', to='UserPost.UserPost')),
                ('userProfileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfileIdOfTheUserWhoGotTaggedInPost', to='UserProfiles.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeTime', models.DateTimeField(auto_now_add=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postIdOfThePostWhichGotLiked', to='UserPost.UserPost')),
                ('userProfileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfileIdOfTheUserWhoLiked', to='UserProfiles.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtagIdInThePostWhichAreUsed', to='Hashtags.Hashtag')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postIdOfThePostWhichGotHashtag', to='UserPost.UserPost')),
                ('userProfileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfiles.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('commentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commentDescription', models.TextField(default='')),
                ('commentTime', models.DateTimeField(auto_now_add=True)),
                ('commentStatus', models.IntegerField(default=0)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postIdOfThePostWhichGotCommented', to='UserPost.UserPost')),
                ('userProfileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfileIdOfTheUserWhoCommented', to='UserProfiles.UserProfile')),
            ],
        ),
    ]
