# Generated by Django 3.0.8 on 2020-11-26 17:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0002_auto_20201122_1412'),
        ('UserPost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='commentDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='postDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PostSubComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCommentId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('commentDescription', models.TextField()),
                ('commentTime', models.DateTimeField(auto_now_add=True)),
                ('commentStatus', models.IntegerField(default=0)),
                ('parentComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserPost.PostComment')),
                ('userProfileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfiles.UserProfile')),
            ],
        ),
    ]
