# Generated by Django 3.0.8 on 2020-11-27 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userProfileId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('userProfilePicture', models.ImageField(blank=True, null=True, upload_to='UserProfile/')),
                ('descriptionOfUser', models.TextField(blank=True, null=True)),
                ('userPhone', models.IntegerField(blank=True, null=True)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
