# Generated by Django 3.1.4 on 2021-06-05 07:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('relationshipId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('relationshipStatus', models.IntegerField(default=0)),
                ('relationshipCreatedTime', models.DateTimeField(auto_now_add=True)),
                ('followerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfileIdOfTheUserWhoIsFollows', to='UserProfiles.userprofile')),
                ('followingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfileIdOfTheUserWhoGotFollowed', to='UserProfiles.userprofile')),
            ],
        ),
    ]
