# Generated by Django 3.0.8 on 2020-11-22 08:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('relationshipId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('relationshipStatus', models.IntegerField()),
                ('relationshipCreatedTime', models.DateTimeField(auto_now_add=True)),
                ('followerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfileIdOfTheUserWhoIsFollows', to='UserProfiles.UserProfile')),
                ('followingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfileIdOfTheUserWhoGotFollowed', to='UserProfiles.UserProfile')),
            ],
        ),
    ]
